# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-04 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageIn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile_number', models.CharField(max_length=150)),
                ('to', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('link_id', models.CharField(default='-1', max_length=15)),
                ('message_id', models.CharField(default='-1', max_length=160)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'messages_in',
                'verbose_name_plural': 'messages in',
            },
        ),
        migrations.CreateModel(
            name='MessageOut',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile_number', models.CharField(max_length=150)),
                ('status', models.CharField(default='-1', max_length=15)),
                ('text', models.TextField()),
                ('link_id', models.CharField(default='-1', max_length=650)),
                ('message_id', models.CharField(default='-1', max_length=160)),
                ('sub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('keyword', models.CharField(default='XX', max_length=150)),
                ('reason', models.TextField()),
            ],
            options={
                'db_table': 'messages_out',
                'verbose_name_plural': 'messages out',
            },
        ),
        migrations.CreateModel(
            name='PredictionText',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('send_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.CharField(max_length=320)),
            ],
            options={
                'db_table': 'prediction_text',
                'verbose_name_plural': 'prediction',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mobile_number', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('sub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('unsub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('keyword', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'subscription',
                'verbose_name_plural': 'subscription',
            },
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set([('mobile_number', 'keyword')]),
        ),
        migrations.AlterUniqueTogether(
            name='predictiontext',
            unique_together=set([('send_date', 'text')]),
        ),
    ]
