# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 20:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictiontext',
            name='send_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
