# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 09:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_auto_20161105_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=320, unique=True)),
            ],
            options={
                'db_table': 'keyword',
                'verbose_name_plural': 'keyword',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionText',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('send_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('text', models.CharField(max_length=320)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.Keyword')),
            ],
            options={
                'db_table': 'subscription_text',
                'verbose_name_plural': 'subscription text',
            },
        ),
        migrations.AlterUniqueTogether(
            name='subscriptiontext',
            unique_together=set([('keyword', 'text', 'send_date')]),
        ),
    ]
