# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 12:19
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_auto_20161105_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnDemandPredictionText',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('send_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('text', models.TextField(max_length=320, unique=True)),
                ('game_id', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'db_table': 'ondemand_prediction_text',
                'verbose_name_plural': 'On Demand Prediction Text',
            },
        ),
        migrations.AlterUniqueTogether(
            name='ondemandpredictiontext',
            unique_together=set([('send_date', 'text', 'game_id')]),
        ),
    ]
