# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_auto_20161108_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagein',
            name='link_id',
            field=models.CharField(default='-1', max_length=415),
        ),
        migrations.AlterField(
            model_name='messagein',
            name='message_id',
            field=models.CharField(default='-1', max_length=460),
        ),
    ]
